---
# tasks file for node_exporter
- name: Install node_exporter on target host
  ansible.builtin.include_tasks: install.yml
  when: state | default("present") == "present"

- name: Uninstall node_exporter on target host
  ansible.builtin.include_tasks: uninstall.yml
  when:  state | default("present") == "absent"