---
- name: Set Download and binary name (amd64)
  ansible.builtin.set_fact:
    download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    binary_path: "{{ download_path }}node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
  when:
    - ansible_distribution != 'Debian'
    - ansible_lsb.id != 'Raspbian'

- name: Set Download and binary name (armv7)
  ansible.builtin.set_fact:
    download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-armv7.tar.gz"
    binary_path: "{{ download_path }}node_exporter-{{ node_exporter_version }}.linux-armv7/node_exporter"
  when:
    - ansible_distribution == 'Debian'
    - ansible_lsb.id == 'Raspbian'